#!/bin/sh
# Build the NON-RELEASE qualification test binary (ADR 0020).
#
#   sh qualification/build.sh [--release]
#
# Generates a separate crate, `redact-secret-gateway-qualification`, under
# qualification/gen/ (git-ignored) from
#   1. a copy of the shipped src/ tree,
#   2. qualification/seam.patch (the ONLY place where a fake-provider path is introduced:
#      it opens the unit-test destination constructors and an init hook in the COPY),
#   3. qualification/overlay/* (new files that exist only in the copy),
#   4. a generated Cargo.toml whose [dependencies] are copied verbatim from the shipped
#      Cargo.toml, and a Cargo.lock derived from the shipped Cargo.lock.
# The shipped package, its sources, features, and lockfile are never modified. The binary is
# named redact-secret-gateway-qualification and must never be uploaded as a candidate
# artifact or published. Prints the path of the built binary on the last line.
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/.." && pwd)"
gen="$here/gen"
profile=debug
profile_flag=""
case "${1:-}" in
  --release) profile=release; profile_flag="--release" ;;
  "") ;;
  *) echo "usage: build.sh [--release]" >&2; exit 2 ;;
esac

rm -rf "$gen"
# Build output lives outside the generated tree so regenerating sources keeps the cache.
CARGO_TARGET_DIR="$here/target"
export CARGO_TARGET_DIR
mkdir -p "$gen/src"
cp -R "$root/src/." "$gen/src/"

# The seam patch must apply cleanly with no fuzz: a drifted source tree fails the build
# loudly instead of silently qualifying something else.
( cd "$gen" && patch -p1 -F0 --no-backup-if-mismatch -s <"$here/seam.patch" )
cp "$here/overlay/qualification.rs" "$gen/src/qualification.rs"
cp "$here/overlay/transport_qualification.rs" "$gen/src/transport/qualification.rs"
cp "$here/overlay/main.rs" "$gen/src/main.rs"

version="$(awk -F'"' '/^version *=/ {print $2; exit}' "$root/Cargo.toml")"
{
  cat <<EOF
# GENERATED by qualification/build.sh. Not the shipped manifest. NON-RELEASE (ADR 0020).
[package]
name = "redact-secret-gateway-qualification"
version = "$version"
edition = "2024"
license = "MIT"
rust-version = "1.88"
description = "NON-RELEASE qualification test build with a loopback fake provider; never ship"
publish = false

# Its own workspace root: this crate is not a member of any other package.
[workspace]

[lib]
name = "redact_secret_gateway"
path = "src/lib.rs"

[[bin]]
name = "redact-secret-gateway-qualification"
path = "src/main.rs"

EOF
  # The shipped [dependencies] block, byte for byte (same pins, same features).
  awk '/^\[dependencies\]/ {on=1; print; next} /^\[/ {on=0} on {print}' "$root/Cargo.toml"
  cat <<EOF

[lints.rust]
unsafe_code = "forbid"
EOF
} >"$gen/Cargo.toml"

# Same dependency versions and checksums as the shipped lockfile, by construction: start
# from it, rename the root package, let cargo prune the dev-only entries, then verify.
sed 's/^name = "redact-secret-gateway"$/name = "redact-secret-gateway-qualification"/' \
  "$root/Cargo.lock" >"$gen/Cargo.lock"
( cd "$gen" && cargo build $profile_flag --quiet 2>&1 ) || { echo "qualification build failed" >&2; exit 1; }

triples() { # name version checksum for every locked package that has a checksum
  awk '/^\[\[package\]\]/ {n="";v="";c=""} /^name = / {gsub(/"/,"",$3); n=$3} /^version = / {gsub(/"/,"",$3); v=$3} /^checksum = / {gsub(/"/,"",$3); print n " " v " " $3}' "$1" | LC_ALL=C sort -u
}
triples "$gen/Cargo.lock" >"$gen/lock.qualification.txt"
triples "$root/Cargo.lock" >"$gen/lock.shipped.txt"
extra="$(LC_ALL=C comm -23 "$gen/lock.qualification.txt" "$gen/lock.shipped.txt" | wc -l | tr -d ' ')"
if [ "$extra" != 0 ]; then
  echo "qualification lock differs from the shipped lock for $extra package(s)" >&2
  exit 1
fi
rm -f "$gen/lock.qualification.txt" "$gen/lock.shipped.txt"
echo "$here/target/$profile/redact-secret-gateway-qualification"
